var GAPIKey='AIzaSyA4oNjb8sArJWMHkB0eMk9amuWWsuwcf7c' //for google Maps
var FCLIENT_ID='LVJO54D0VKC0UELX4IA43NT4YWFIUBW0O05B0VRA41LQ2J43' //for FourSquare Client ID
var FCLIENT_SEC='YLQ3VUVGFCMG0WUXPDOXB3KNBJR5O5KEO4ZIHXHYBGDUWOV3' //for FourSquare Client Secret

export {GAPIKey,FCLIENT_ID,FCLIENT_SEC}